### PR TITLE
[feat] autocomplete for questions

### PR DESCRIPTION
**Pull request by fabio-ivona**
This PR will add autocomplete feature for ask/Question 

here's the resulting prompt:

https://user-images.githubusercontent.com/8792274/188404964-8d521a32-3a3d-4a7d-8e54-2e99d5c886da.mp4

### CODE REVIEW

**Review by xiCO2k — APPROVED** [review]

**Comment by fabio-ivona** [comment]
Will check in a while the failing test for PHP8.0

**Comment by fabio-ivona** [comment]
@xiCO2k would you mind to try executing tests in your local environment? I don't see them fail on my machine, I'm wondering if it is a workflows environment issue

**Comment by xiCO2k** [comment]
All passing local as well.

**Comment by fabio-ivona** [comment]
That's weird, maybe this fails in workflows because it detects there's not interactive terminal?

**Comment by xiCO2k** [comment]
Definately possible, we may need to check on Symfony Console source how they test that stuff.

**Comment by fabio-ivona** [comment]
> Definately possible, we may need to check on Symfony Console source how they test that stuff.

They gave up too :rofl: 

image

I updated the test adding a skip if `stty` is not available and added a test to ensure autocomplete values are set in Symfony Question

**Review by xiCO2k — APPROVED** [review]

**Comment by roberto910907** [comment]
@nunomaduro can we merge this PR, please?

**Comment by fabio-ivona** [comment]
@xiCO2k  I updated the code merging from #156 

I guess that switching from 

```php
 return $output->ask($html);
```

to

```php
 return $output->askQuestion($question);
```

should solve the conflict, but it would be great if you could have a look at it too

**Comment by fabio-ivona** [comment]
@xiCO2k I updated the code merging from https://github.com/nunomaduro/termwind/pull/156

I guess that switching from

 return $output->ask($html);
to

 return $output->askQuestion($question);
should solve the conflict, but it would be great if you could have a look at it too

**Comment by xiCO2k** [comment]
Will check @fabio-ivona

**Comment by fabio-ivona** [comment]
@xiCO2k  phpstan errors fixed in #158

**Comment by xiCO2k** [comment]
Thanks

**Review by xiCO2k — APPROVED** [review]

**Comment by xiCO2k** [comment]
Looks good to me, @nunomaduro thoughts?

**Pull request merged**
