### PR TITLE
Add support for table tags

### PR DESCRIPTION
**Pull request by butschster**
```php
render(<<<'HTML'
<table style="box-double">
    <thead title="Books" class="bg-red text-color-white px-10">
        <tr>
            <th align="right">ISBN</th>
            <th>Title</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th align="right">99921-58-10-7</th>
            <td>Divine Comedy</td>
            <td align="right">Dante Alighieri</td>
        </tr>
        <tr border="1">
            <th class="bg-blue text-color-red" align="right">9971-5-0210-0</th>
            <td>A Tale of Two Cities</td>
            <td align="right">Charles Dickens</td>
        </tr>
        <tr>
            <th align="right">960-425-059-0</th>
            <td>The Lord of the Rings</td>
            <td align="right">J. R. R. Tolkien</td>
        </tr>
        <tr>
            <th align="right">80-902734-1-6</th>
            <td>And Then There Were None</td>
            <td rowspan="2" align="right">Dante Alighieri\nspans multiple rows</td>
        </tr>
        <tr>
            <th align="right">978-052156781</th>
            <td>De Monarchia</td>
        </tr>
    </tbody>
    <tfoot title="Page 1/2" class="mx-5 bg-blue">
        <tr>
            <th colspan="3">This value spans 3 columns.</th>
        </tr>
    </tfoot>
</table>
HTML);
```

**Will render**
table

### CODE REVIEW

**Comment by butschster** [comment]
I've completely forgot about table properties.

<table style="..."> has one of symfony table styles. See https://github.com/symfony/console/blob/5.3/Helper/Table.php#L843

I added also support for colspan, rowspan

**Comment by butschster** [comment]
table

**Comment by xiCO2k** [comment]
Great printscreen haha :D.

**Comment by butschster** [comment]
> Great printscreen haha 👌

It's figma :) I liked your one.

**Pull request merged**
