### PR TITLE
[Feature] Style inheritance

### LINKED ISSUE #53: Elements with classes that apply escape codes do not work with classes that manipulate the content
Since #52 was merged, classes like `font-bold` `italic` `underline` `line-through` `invisible` are wrapping the content of the element with escape codes.

But classes like `uppercase`, `truncate`, `snacecase` are transforming the content of the element.

So when these classes are combined, e.g. `font-bold uppercase`, the escape codes will be capitalized which breaks them.
Also, if the classes are set in reverse order, e.g. `uppercase font-bold` this does not happen because the classes are applied in the order they appear (it should not).

### PR DESCRIPTION
**Pull request by butschster**
I split Element class into Element and Styles

Now Styles object is responsible for the element styles. It accumulates rules, text modifiers and style modifiers, then Element passes a text string into this object and it applies at first text modifiers, then style modifiers and finally adds style tags.

This PR fixes #53 issue

### CODE REVIEW

**Comment by xiCO2k** [comment]
Tested this one:

```php
render(<<<'HTML'
    <div class="my-1 ml-3 px-2 bg-green-300 text-black">
        🍃 Termwind <span class="text-red-500"><span class="text-blue-300">now <span class="text-indigo-500">have</span> the</span> capability</span> to extend colors!
    </div>
HTML);
```

Renders:
image


Not most real use case 😄 😄 😄 😄

**Comment by butschster** [comment]
> Tested this one:
> 
> ```
> render(<<<'HTML'
>     <div class="my-1 ml-3 px-2 bg-green-300 text-black">
>         🍃 Termwind <span class="text-red-500"><span class="text-blue-300">now <span class="text-indigo-500">have</span> the</span> capability</span> to extend colors!
>     </div>
> HTML);
> ```
> 
> Renders: image
> 
> Not most real use case 😄 😄 😄 😄

It was quite difficult, but perhaps I nailed it! :) @xiCO2k another example!

**Comment by xiCO2k** [comment]
Respect! 🙇  🙇  🙇 

image

Thanks @butschster.

Will make a few more tests

**Comment by butschster** [comment]
> Respect! 🙇 🙇 🙇
> 
> image
> 
> Thanks @butschster.
> 
> Will make a few more tests

There is another problem! italic and underline both don't have alternative as part of `options` attribute. We can not cover all cases.

**Review by xiCO2k — APPROVED** [review]

**Comment by xiCO2k** [comment]
Hey @nunomaduro can you take a look on this PR? Thanks.

**Review by nunomaduro — APPROVED** [review]

**Pull request merged**
